services:
  - type: web
    name: wishnet-dashboard
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0

    envVars:
      - key: MONGODB_URI
        sync: false

      - key: MONGODB_DB
        sync: false

      - key: WISHNET_USERNAME
        sync: false

      - key: WISHNET_PASSWORD
        sync: false
